services:
  proxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxymanager
    restart: unless-stopped
    ports:
      - "81:81"
      - "88:80"
      - "8443:443"
    volumes:
      - nginx_data:/data
      - ${HOME}/.config/letsencrypt:/etc/letsencrypt
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "10180:80"
    volumes:
      - filebrowser_data:/data
      - filebrowser_srv:/srv
    environment:
      - TZ=UTC
      - UID=1000
      - GID=1000
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbit_data:/config
      - /DATA/downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"

networks:
  default:
    name: nginx-ssl

volumes:
  nginx_data:
    external: true
  portainer_data:
    external: true
  filebrowser_srv:
  filebrowser_data:
    external: true
  qbit_data:
    external: true

