services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    networks:
      - xlocal
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-latest}
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    networks:
      - xlocal
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - '${CONFIG}/jellyfin:/config'
      - ${HOME}/.cache/jellyfin:/cache
      - type: bind
        source: ${DATA_MEDIA}
        target: /media
        bind:
          propagation: shared
    environment:
      - TZ=${TZ}
      - PUID=${HOST_UID}
      - PGID=${HOST_GID}
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    networks:
      - xlocal
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MARIADB_AUTO_UPGRADE=1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql
    # Security Best Practice:  Consider *not* exposing the MariaDB port.  Nextcloud
    # communicates with it via the Docker network.  No ports section here.
    # ports:
    #   - "3306:3306" #  DO NOT UNCOMMENT THIS LINE UNLESS YOU HAVE A SPECIFIC REASON
  redis:
    image: redis:${REDIS_VERSION:-latest}
    container_name: redis
    hostname: redis
    restart: unless-stopped
    networks:
      - xlocal
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION:-latest}
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    networks:
      - xlocal
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - nextcloud_app:/var/www/html         # Named volume for Nextcloud application code
      - nextcloud_data:/var/www/html/data   # volume for nextcloud data
      - type: bind                          # Mount user data.  Use a named volume if possible.
        source: ${DATA_CLOUD}
        target: /mnt/cloud
        bind:
          propagation: shared
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
    #Recommended
      - PHP_UPLOAD_LIMIT=16G
      - PHP_MEMORY_LIMIT=512M
      - NEXTCLOUD_MAX_UPLOAD_SIZE=16G
      # Security hardening (from Nextcloud documentation)
      #- OVERWRITEPROTOCOL=https #Enforce HTTPS
      #- TRUSTED_PROXIES=172.16.0.0/12,192.168.1.0/16
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - NEXTCLOUD_OVERWRITE_WEBROOT=/nextcloud
      - NEXTCLOUD_ENABLE_MAIL=false

# Network
networks:
  xlocal:
    driver: bridge

# Volumes
volumes:
  portainer_data:
    external: true
  mariadb_data:
    driver: local
  redis_data:
  nextcloud_app:
    driver: local
  nextcloud_data:
    driver: local
