services:
  proxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxymanager
    restart: unless-stopped
    ports:
      - "81:81"
      - "88:80"
      - "8443:443"
    volumes:
      - nginx_data:/data
      - ${HOME}/.config/letsencrypt:/etc/letsencrypt
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - ${HOME}/.config/jellyfin:/config
      - ${HOME}/.cache/jellyfin:/cache
      - type: bind
        source: ${DATA_MEDIA}
        target: /media
        bind:
          propagation: shared
    environment:
      - TZ=${TZ}
      - PUID=${HOST_UID}
      - PGID=${HOST_GID}
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud
    restart: unless-stopped
    ports:
      - ${OWNCLOUD_PORT}:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - owncloud:/mnt/data
      #https://doc.owncloud.com/server/next/admin_manual/configuration/files/external_storage/local.html
      - type: bind
        source: ${DATA_CLOUD}
        target: /owncloud
        bind:
          propagation: shared
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:6
    container_name: redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data

# Network
networks:
  default:
    name: nginx-ssl

# Volumes
volumes:
  nginx_data:
    external: true
  portainer_data:
    external: true
  mysql:
    driver: local
  redis:
    driver: local
  owncloud:
    driver: local

